---
title: "tidy_data"
output: html_document
date: "Last update: `r Sys.Date()`"
---

# libs

```{r}
#| label: setup
#| warning: false
#| message: false
library("dplyr")
library("tidyr")
library("readr")
library("here")
library("fs")
library("forcats")
library("stringr")
library("purrr")
library("readxl")
library("ggplot2")
library("lme4")
library("marginaleffects")
```

# Load and tidy data

## Local data

```{r}
#| label: load-local-data
#| message: false
# Load local csvs 
# except 
#  - 028_exp_g2_2023-05-05_15h19.23.523.csv (because it has more columns)

local_temp1 <- dir_ls(here("dat", "raw_local"), regexp = ".csv") |> 
  as_tibble() |> 
  filter(
    value != here("dat", "raw_local", "028_exp_g2_2023-05-05_15h19.23.523.csv")
  ) |> 
  pull() |> 
  map_dfr(
    read_csv, 
    id = "source", 
    col_types = cols(.default = "c")
  ) |> 
  filter(exp_num == 2, lang %in% c("en", "es")) |> 
  filter(case_when(exp2_key.keys == '["lshift","rshift"]' |
                 exp2_key.keys == "['lshift', 'rshift']"
                 ~ cs=='1',
                 exp2_key.keys == '["lshift"]' |
                 exp2_key.keys == "['lshift']"
                 ~ cs!='1' )) %>% 
  transmute(
    
    participant, 
    group = expName, 
    list, cond, lang, type, num, 
    exp_num, 
    cs, 
    response = exp2_key.keys, 
    rt = exp2_key.rt 
    )

# load 
#  - 028_exp_g2_2023-05-05_15h19.23.523.csv (because it has more columns)
local_temp28 <- read_csv(
  here("dat", "raw_local", "028_exp_g2_2023-05-05_15h19.23.523.csv")
  ) |>
  filter(exp_num == 2, lang %in% c("en", "es")) |> 
  transmute(
    participant = as.character(participant), 
    group = expName, 
    list, cond, lang, type, num, 
    exp_num = as.character(exp_num), 
    cs = as.character(cs), 
    response = exp2_key.keys, 
    #rt = as.numeric(str_remove_all(exp2_key.rt, "\\[|\\]")), 
        rt = exp2_key.rt, 
  )

# Combine local in single df
df_local <- bind_rows(local_temp1, local_temp28) |> 
  mutate(source = "local") %>% 
  filter(., cs == 1) %>% 
  separate(col = rt, into = c('rt1', 'rt2'), sep = ',', fill = "right") %>% 
  mutate(rt1 = as.numeric(stringr::str_remove_all(rt1, "\\[")), 
         rt2 = as.numeric(stringr::str_remove_all(rt2, "\\]"))) %>% 
  select (., participant, group, list, cond, lang, type, num, exp_num, cs, response, rt1, rt2)
```


## Online data

```{r}
#| label: load-online-data
#| message: false
# Load online csvs 
# These files all have different columns names/numbers
#  - 021_exp_g1_2023-09-05_18h32.55.031
#  - 027_exp_g2_2023-10-18_14h15.06.123
#  - 029_exp_g2_2023-10-21_17h02.18.335
#  - 033_exp_g2_2023-10-12_11h56.31.376
#  - 042_exp_g1_2023-09-29_14h14.23.677
#  - 054_exp_g2_2023-10-12_12h40.24.192
#  - 062_exp_g2_2023-11-16_11h11.01.336
#  - 064_exp_g2_2023-10-23_17h51.37.190
#  - 067_exp_g2_2023-10-18_16h58.16.959
#  - 070_exp_g1_2023-09-22_13h39.35.259
#  - 073_exp_g2_2023-09-11_17h01.16.888
#  - 074_exp_g2_2023-10-06_10h15.54.848
#  - 075_exp_g2_2023-10-12_11h13.11.698
#  - 086_exp_g1_2023-09-19_11h05.55.100
#  - 091_exp_g2_2023-09-14_12h03.00.504

# Put them in a list: 
temp_list <- dir_ls(here("dat", "raw_online"), regexp = ".csv") |> 
  as.list() |> 
  map(read_csv)

# Make vector of only the columns we want
my_cols <- c(
  "participant", "expName", "list", "cond", "lang", "type", "num", "exp_num",
  "cs", "exp2_key.keys", "exp2_key.rt" 
)

# Select only the columns in my_cols in each df in the list
temp_list <- Map(function(x){x[,names(x) %in% my_cols]}, temp_list)

# Bind them all into one df
df_online <- do.call("rbind", temp_list) |> 
  filter(exp_num == 2, lang %in% c("en", "es"), !is.na(list)) |> 
  transmute(
    participant = as.character(participant), 
    group = expName, 
    list, cond, lang, type, num, 
    exp_num = as.character(exp_num), 
    cs = as.character(cs), 
    response = exp2_key.keys, 
        rt = exp2_key.rt,
  ) |> 
  mutate(source = "online") %>% 
  filter(., cs == 1) %>% 
  separate(col = rt, into = c('rt1', 'rt2'), sep = ',', fill = "right") %>% 
  mutate(rt1 = as.numeric(stringr::str_remove_all(rt1, "\\[")), 
         rt2 = as.numeric(stringr::str_remove_all(rt2, "\\]"))) %>% 
  select (., participant, group, list, cond, lang, type, num, exp_num, cs, response, rt1, rt2)
```

## Combine everything

```{r}
#| label: combine-online-local
#| message: false
# Combine df_local and df_online
df_complete <- bind_rows(df_local, df_online) |> 
  mutate(
    participant = str_pad(participant, pad = "0", width = 3), 
    num = str_remove(num, "\\.0"), 
    num = str_pad(num, pad = "0", width = 3)
  ) |> 
  # Join with lextale data
  left_join(
    read_csv(here("dat", "lang_bg", "lang_bg.csv")) |> 
    select(participant, lextale) |> 
    mutate(
      participant = as.character(participant), 
      participant = str_pad(participant, side = "left", pad = "0", width = 3), 
      lextale_z = (lextale - mean(lextale)) / sd(lextale)
      ), 
    by = "participant"
  ) |> 
  # Join with matrix duration data
  left_join(
    read_excel(here("exp", "stim_new", "stimuli_all.xlsx")) |> 
    mutate(
      num = str_remove(num, "\\.0"), 
      num = str_pad(num, pad = "0", width = 3)
    ) |> 
    filter(
      mat_dur != "-", 
      lang %in% c("en", "es"), 
      list %in% c("l1", "l2"), 
      cond %in% c("t", "f"), 
      type %in% c("na", "f0c", "f0u")
    ) |> 
    select(num, mat_dur), 
    by = "num"
  ) |> 
  filter(!is.na(mat_dur)) |> 
  mutate(rt_mat = as.numeric(rt2) - as.numeric(mat_dur)) |> 
  mutate(rt_cs = as.numeric(rt2) - as.numeric(rt1)) %>% 
  filter(rt_mat > 0 & rt_cs > 0) |> 
  write_csv(here("dat", "exp2_clean_jvc.csv"))

```






# plot

```{r}
#| label: plot-rts
#| dpi: 300
#| fig-asp: 0.56
#| out-width: "100%"

#calculate limit
df_limit<-df_complete %>% 
  group_by(participant) %>% 
  summarize(ave1 = mean(rt1), limit1 = ave1 + sd(rt1)*2,
            ave2 = mean(rt2), limit2 = ave2 + sd(rt2)*2)

df_ltd<-df_complete%>% 
  left_join(., df_limit, by = 'participant')
  
#combine limit and make plots
#mat_rt plot
 df_ltd %>% 
   filter(., rt1 <= limit1 & rt2 <= limit2) %>% 
   filter(., response == '["lshift","rshift"]' |
         response == "['lshift', 'rshift']") %>% 
   group_by(participant) %>% 
  ggplot() +
  aes(x = interaction(type, lang), y = rt_mat) +
  geom_point(color = "magenta", alpha = 0.3) +
  stat_summary(fun.data = mean_sdl, geom = "pointrange", pch = 21, fill = 'white') +
  stat_summary(
    fun.data = mean_se, size = 4,
    geom = "text", 
    aes(label = sprintf("%0.2f", round(after_stat(y), digits = 2))),
    position = position_nudge(x = 0.25)
  ) +
  labs(
    x = "Conditions", 
    y = "MatrixReaction Time", 
    title = "EXP2 Matrix RT as a function of Cond",
    caption = "Matrix RT as a function of Cond"
  ) 
 
#cs_dur plot
 df_ltd %>% 
   filter(., rt1 <= limit1 & rt2 <= limit2) %>% 
   filter(., response == '["lshift","rshift"]' |
         response == "['lshift', 'rshift']") %>% 
   group_by(participant) %>% 
  ggplot() +
  aes(x = interaction(type, lang), y = rt_cs) +
  geom_point(color = "magenta", alpha = 0.3) +
  stat_summary(fun.data = mean_sdl, geom = "pointrange", pch = 21, fill = 'white') +
  stat_summary(
    fun.data = mean_se, size = 4,
    geom = "text", 
    aes(label = sprintf("%0.2f", round(after_stat(y), digits = 2))),
    position = position_nudge(x = 0.25)
  ) +
  labs(
    x = "Conditions", 
    y = "CSReaction Time", 
    title = "EXP2 CS RT as a function of Cond",
    caption = "CS RT as a function of Cond"
  ) 

df_ltd |> 
  filter(rt1 <= limit1 & rt2 <= limit2) %>% 
   filter(., response == '["lshift","rshift"]' |
         response == "['lshift', 'rshift']") |> 
  ggplot() + 
  aes(x = lextale_z, y = rt_mat, color = interaction(lang, type)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(method = lm, se = F, fullrange = T, formula = "y ~ x") + 
  scale_color_viridis_d(name = NULL, end = 0.8)

```

```{r, this part is much more complicated for exp2}
#| label: plot-accuracy
#| dpi: 300
#| fig-asp: 0.56
#| out-width: "100%"
df_ltd %>% 
   mutate(., is_correct = ifelse(response == '["lshift","rshift"]' |
         response == "['lshift', 'rshift']", 1, 0)) %>% 
  ggplot(.,) + 
  aes(x = type, y = is_correct, fill = lang) + 
  geom_jitter(
    data = df_complete |> 
      group_by(participant, type, lang) |> 
      summarize(avg = mean(is_correct, na.rm = T), .groups = "drop"), 
    aes(x = type, y = avg, color = lang), 
    height = 0, width = 0.2
  ) + 
  stat_summary(
    fun.data = mean_se, geom = "pointrange", pch = 21, 
    position = position_dodge(0.5)
  ) + 
  scale_fill_viridis_d(name = NULL, end = 0.8) + 
  scale_color_viridis_d(name = NULL, end = 0.8)
```



# Models

```{r}
#| label: model

df_mod <- df_ltd |> 
  filter(is_correct == 1) |> 
  unite(col = condition, c("lang", "type"), sep = "-") |> 
  mutate(
    log_rt = log(rt), 
    condition = fct_relevel(condition, "es-na")
  ) 

mod_lt <- lmer(
  log_rt ~ lextale_z * condition + (1 | participant), 
  data = df_mod
)

mod_1 <- lmer(
  log_rt ~ 1 +  condition + (1 | participant), 
  data = df_mod
)
summary(mod_lt)
```

